### PR TITLE
Dynamic type checking for the cython integrator

### LINKED ISSUE #3: Add in type checker for Cython solver
Right now the cython solver only works with complex-valued y-values. You can still solve purely real valued problems with it but the initial conditions must be provided as a complex ndarray (with the imaginary portion zero'd out). This is obviously not ideal from a user-perspective and I would suspect there is a performance hit if complex values are not required. 

Ideally, a type checker must be implemented in the cython code which will dynamically change based on the user's input. 

Worst case scenario, two versions of the cython solver could be made and then a wrapper can be created that picks which one to use based on the user input (or a user could import the proper function directly).

### PR DESCRIPTION
**Pull request by dihm**
I have been enjoying becoming familiar with this package and I am very grateful for all your work. I'm hoping to incorporate it into a project I'm working on that largely relies on scipy's solve_ivp and could really benefit from these compiled speed ups. However, our systems are always real and it would be nice if the cython solver could handle that natively. So I decided to try my hand at it. 

Assuming I've used an appropriate strategy, I still think there is some work to be done. I've created the PR with these nominally functional changes so I can get your input before getting too much further into the weeds.

Summary of changes:

- Implementation relies on fused types on the `y0` input array, which now uses a typed memory view.
- For convenience (possibly necessity), I've removed a bunch of the older numpy buffer cdefs. Tests on toy code seem to indicate they are not needed if a corresponding typed memory view assigned to the output of the numpy allocators is used anyway.
- I've also recast all the RK constants to doubles and rely on cython to correctly cast them to double complex when necessary.

My tests to confirm functionality are using the Benchmark notebook (read very thorough). Timing seems to indicate current changes make cython marginally slower and solving the system in the complex or real domains makes little difference.

Current main:
```shell
end_time-1.0e-03: Numba=8.378x; Cython=3.822x; NbCy=2.192x
end_time-1.0e-02: Numba=8.559x; Cython=3.555x; NbCy=2.408x
end_time-1.0e-01: Numba=12.188x; Cython=5.894x; NbCy=2.068x
end_time-1.0e+00: Numba=22.942x; Cython=9.347x; NbCy=2.455x
end_time-1.0e+01: Numba=57.074x; Cython=17.350x; NbCy=3.290x
end_time-1.0e+02: Numba=78.991x; Cython=17.529x; NbCy=4.506x
```

This PR using complex128 init conditions
```shell
end_time-1.0e-03: Numba=9.116x; Cython=2.935x; NbCy=3.106x
end_time-1.0e-02: Numba=8.152x; Cython=3.228x; NbCy=2.526x
end_time-1.0e-01: Numba=11.573x; Cython=4.130x; NbCy=2.802x
end_time-1.0e+00: Numba=22.433x; Cython=7.619x; NbCy=2.944x
end_time-1.0e+01: Numba=61.345x; Cython=15.186x; NbCy=4.040x
end_time-1.0e+02: Numba=76.801x; Cython=15.907x; NbCy=4.828x
```

This PR using float64 init conditions
```shell
end_time-1.0e-03: Numba=8.905x; Cython=2.677x; NbCy=3.327x
end_time-1.0e-02: Numba=8.743x; Cython=2.878x; NbCy=3.038x
end_time-1.0e-01: Numba=11.581x; Cython=4.065x; NbCy=2.849x
end_time-1.0e+00: Numba=24.044x; Cython=7.426x; NbCy=3.238x
end_time-1.0e+01: Numba=58.090x; Cython=17.026x; NbCy=3.412x
end_time-1.0e+02: Numba=68.875x; Cython=18.026x; NbCy=3.821x
```

Finally, I have not tested the interpolation or capture_extra functionality at all. I strongly suspect there are runtime issues to be fixed there as well.

Fixes #3

### CODE REVIEW

**Comment by dihm** [comment]
Found a few operations that weren't using the memory views. That seems to have brought things closer to original performance. Real vs complex is still the same though.

This PR with complex128
```shell
end_time-1.0e-03: Numba=9.005x; Cython=3.190x; NbCy=2.823x
end_time-1.0e-02: Numba=9.405x; Cython=3.729x; NbCy=2.522x
end_time-1.0e-01: Numba=12.645x; Cython=4.688x; NbCy=2.698x
end_time-1.0e+00: Numba=21.918x; Cython=7.702x; NbCy=2.846x
end_time-1.0e+01: Numba=59.008x; Cython=16.353x; NbCy=3.608x
end_time-1.0e+02: Numba=72.778x; Cython=17.688x; NbCy=4.115x
```

This PR with float64
```shell
end_time-1.0e-03: Numba=9.950x; Cython=3.315x; NbCy=3.002x
end_time-1.0e-02: Numba=9.236x; Cython=2.915x; NbCy=3.168x
end_time-1.0e-01: Numba=13.365x; Cython=4.280x; NbCy=3.123x
end_time-1.0e+00: Numba=23.835x; Cython=7.666x; NbCy=3.109x
end_time-1.0e+01: Numba=57.536x; Cython=17.307x; NbCy=3.325x
end_time-1.0e+02: Numba=67.786x; Cython=18.061x; NbCy=3.753x
```

**Comment by jrenaud90** [comment]
Hey @dihm! This is awesome and definitly something that was on the todo list. I will be able to sit down and look at it better early next week, but a quick glance I think this should be good to push. And yes there was a lot of cleaning up of unused variables that I had been doing locally but hadn't pushed yet. Thanks for tackling those!

**Review by jrenaud90 — APPROVED** [review]
@dihm - I had to make some changes to get all the tests to past, but it looks like we are in good shape now. I am merging this onto a new branch for v0.5.0 which will get a few other updates before merging into main. Please feel free to check the tests you have been doing locally to see if you notice any issues. Thanks again for the PR!

**Comment by dihm** [comment]
Glad I could help out. Your test suite is significantly more thorough than mine so I'll assume everything is working well. I look forward to incorporating this into my other project. I suspect it is going to be a huge help.

Thanks again for putting the time in to make this package so nice!

**Comment by jrenaud90** [comment]
Thanks for your help! The changes are now pushed to main. fyi there is some weirdness going on with compiling on macs. It should work if you download the source from the [release](https://github.com/jrenaud90/CyRK/releases/tag/v0.5.0) and `pip install -v .` it locally but it won't be up on pypi until I can figure it out. So `pip install cyrk` won't work for the time being.

**Pull request merged**
